language: node_js
sudo: false
node_js:
  - "5"
  - "0.10"
  - "0.12"
  - "4"
git:
  depth: 10
before_install:
  - "npm config set registry https://:2016-03-02T18%3A09%3A40.696Z@time-machines-npm.sealsecurity.io/"
  - "nvm use $TRAVIS_NODE_VERSION"
  - "npm set loglevel error"
  - "npm set progress false"
  - "npm i -g npm@\"^2.0.0\" --registry=https://:2016-03-02T18%3A09%3A40.696Z@time-machines-npm.sealsecurity.io/"
install:
  - "npm install --registry=https://:2016-03-02T18%3A09%3A40.696Z@time-machines-npm.sealsecurity.io/ qunitjs@~1.22.0 qunit-extras@^1.5.0 lodash@4.5.0 async@^1.5.2 fs-extra@~0.26.5 glob@^7.0.0 uglify-js@2.6.2"
before_script:
  - "node ./lib/main/build-dist.js"
script:
  - "cd ./test"
  - "node ./test.js ../lodash.js"
  - "node ./test.js ../dist/lodash.min.js"
  - "node ./test-fp.js"
